import json

# Cell 0 source: fixed to patch pyproject.toml for Python 3.10 / Kaggle environment
CELL0 = (
    "import os, subprocess, sys, re, pathlib\n"
    "if not os.path.exists('/kaggle/working/bubbleml-submission'):\n"
    "    os.system('git clone https://github.com/RealmeBTI/bubbleml-submission.git /kaggle/working/bubbleml-submission')\n"
    "REPO = '/kaggle/working/bubbleml-submission'\n"
    "subprocess.run(['git', 'checkout', 'afe4ba121fa50b58cc3c3001a17087c069766366'], check=True, cwd=REPO)\n"
    "\n"
    "# Patch pyproject.toml so pip install -e . works on Kaggle (Python 3.10, older deps)\n"
    "pf = pathlib.Path(REPO) / 'pyproject.toml'\n"
    "txt = pf.read_text()\n"
    "# Remove Python version gate\n"
    "txt = re.sub(r'requires-python\\s*=\\s*\">=3\\.\\d+\\.\\d+\"', 'requires-python = \">=3.10.0\"', txt)\n"
    "# Remove pinned torch (will install separately)\n"
    "txt = re.sub(r'\\s*\"torch==[^\"]+\",?\\n', '\\n', txt)\n"
    "# Replace incompatible dep pins with flexible minimums that have py310 wheels\n"
    "txt = re.sub(r'\"h5py==[^\"]+\"', '\"h5py>=3.7.0\"', txt)\n"
    "txt = re.sub(r'\"matplotlib==[^\"]+\"', '\"matplotlib>=3.5.0\"', txt)\n"
    "txt = re.sub(r'\"numpy==[^\"]+\"', '\"numpy>=1.23.0\"', txt)\n"
    "txt = re.sub(r'\"scipy==[^\"]+\"', '\"scipy>=1.9.0\"', txt)\n"
    "txt = re.sub(r'\"tensorly==[^\"]+\"', '\"tensorly>=0.8.0\"', txt)\n"
    "txt = re.sub(r'\"opt_einsum==[^\"]+\"', '\"opt_einsum>=3.3.0\"', txt)\n"
    "pf.write_text(txt)\n"
    "print('pyproject.toml patched:')\n"
    "print(pf.read_text())\n"
    "\n"
    "# Install pinned torch first, then the package\n"
    "subprocess.run([sys.executable, '-m', 'pip', 'install',\n"
    "    'torch==2.2.2', 'torchvision==0.17.2',\n"
    "    '--index-url', 'https://download.pytorch.org/whl/cu121'], check=True)\n"
    "subprocess.run([sys.executable, '-m', 'pip', 'install', '-e', '.'], check=True, cwd=REPO)\n"
    "print('Setup complete.')\n"
)

# All remaining cells copied verbatim from the user's final_checked notebook
CELL1 = (
    "import urllib.request, pathlib, subprocess, shutil, sys\n"
    "WORK = pathlib.Path('/kaggle/working')\n"
    "ARCHIVE = WORK / 'bubbleml_data/archive/pool-boiling-subcooled.tar.gz'\n"
    "ARCHIVE.parent.mkdir(parents=True, exist_ok=True)\n"
    "if not ARCHIVE.exists():\n"
    "    print('Downloading dataset (1.6 GB)...')\n"
    "    url = 'https://bubble-ml-simulations.s3.us-east-2.amazonaws.com/pool-boiling-subcooled-fc72-2d.tar.gz'\n"
    "    urllib.request.urlretrieve(url, ARCHIVE)\n"
    "    print('Download complete.')\n"
)

CELL2 = (
    "import subprocess, pathlib, sys, shutil, json\n"
    "WORK = pathlib.Path('/kaggle/working')\n"
    "ARCHIVE = WORK / 'bubbleml_data/archive/pool-boiling-subcooled.tar.gz'\n"
    "HDF5_DIR = WORK / 'bubbleml_data/hdf5_tmp'\n"
    "DATA48 = WORK / 'bubbleml_data/tutorial_48x48'\n"
    "REPO = WORK / 'bubbleml-submission'\n"
    "HDF5_DIR.mkdir(parents=True, exist_ok=True)\n"
    "\n"
    "import tarfile\n"
    "print('Opening tarfile...')\n"
    "with tarfile.open(ARCHIVE, 'r:gz') as tar:\n"
    "    for member in tar.getmembers():\n"
    "        if member.name.endswith('Twall-103.hdf5') or member.name.endswith('Twall-106.hdf5') or member.name.endswith('Twall-100.hdf5'):\n"
    "            print('Extracting', member.name)\n"
    "            member.name = pathlib.Path(member.name).name\n"
    "            tar.extract(member, path=HDF5_DIR)\n"
    "if not DATA48.exists():\n"
    "    print('Running preprocess (48x48)...')\n"
    "    subprocess.run([\n"
    "        sys.executable, '-m', 'bubbleml_benchmark.prepare',\n"
    "        '--input-dir', str(HDF5_DIR),\n"
    "        '--output-dir', str(DATA48),\n"
    "        '--start-step', '30',\n"
    "        '--rollout-steps', '5',\n"
    "        '--stride', '1',\n"
    "        '--target-resolution', '48',\n"
    "        '--train-sources', 'Twall-103.hdf5',\n"
    "        '--val-sources', 'Twall-106.hdf5',\n"
    "        '--test-sources', 'Twall-100.hdf5',\n"
    "        '--nan-policy', 'error',\n"
    "    ], cwd=str(REPO), check=True)\n"
    "\n"
    "if HDF5_DIR.exists(): shutil.rmtree(HDF5_DIR)\n"
    "print('Preprocessing complete.')\n"
)

CELL3_LINES = [
    "import gc\n",
    "import platform\n",
    "import sys\n",
    "import torch\n",
    "\n",
    "print('--- BubbleML Runtime Check ---')\n",
    "print('Python:', sys.version.split()[0])\n",
    "print('PyTorch:', torch.__version__)\n",
    "print('CUDA available:', torch.cuda.is_available())\n",
    "print('CUDA build:', torch.version.cuda)\n",
    "\n",
    "if not torch.cuda.is_available():\n",
    "    raise RuntimeError(\n",
    "        'CUDA is not available in this runtime. '\n",
    "        'Run this notebook on a GPU-enabled Kaggle session, then rerun from Cell 3.'\n",
    "    )\n",
    "\n",
    "device_index = torch.cuda.current_device()\n",
    "capability = torch.cuda.get_device_capability(device_index)\n",
    "device_name = torch.cuda.get_device_name(device_index)\n",
    "print(f'GPU: {device_name} (compute capability {capability[0]}.{capability[1]})')\n",
    "\n",
    "# Fail early for known-incompatible/too-old CUDA environments rather than failing deep inside training.\n",
    "if torch.version.cuda is None:\n",
    "    raise RuntimeError('This PyTorch installation has no CUDA runtime.')\n",
    "if capability[0] < 7:\n",
    "    print(\n",
    "        'Warning: this GPU has a relatively old compute capability. '\n",
    "        'The pinned PyTorch/CUDA stack may not support it reliably.'\n",
    "    )\n",
    "\n",
    "print('--- CUDA Smoke Test ---')\n",
    "try:\n",
    "    torch.cuda.empty_cache()\n",
    "    dummy_input = torch.randn(2, 5, 48, 48, device='cuda')\n",
    "    conv = torch.nn.Conv2d(5, 5, kernel_size=3, padding=1, device='cuda')\n",
    "    out = conv(dummy_input)\n",
    "    loss = out.square().mean()\n",
    "    loss.backward()\n",
    "    torch.cuda.synchronize()\n",
    "\n",
    "    assert out.shape == dummy_input.shape, (\n",
    "        f'Unexpected smoke-test output shape: {tuple(out.shape)}'\n",
    "    )\n",
    "    print('Smoke test PASSED: forward, backward, and CUDA synchronization all succeeded.')\n",
    "finally:\n",
    "    # Release the temporary tensors before the expensive training cells.\n",
    "    for obj_name in ('dummy_input', 'conv', 'out', 'loss'):\n",
    "        globals().pop(obj_name, None)\n",
    "    gc.collect()\n",
    "    torch.cuda.empty_cache()\n",
    "\n",
    "print('Cell 3 validation complete. Safe to continue with Cell 4.')\n",
]

CELL4_LINES = [
    "import json\n",
    "import pathlib\n",
    "import torch\n",
    "\n",
    "WORK = pathlib.Path('/kaggle/working')\n",
    "EXP_DIR = WORK / 'experiments'\n",
    "CHK_DIR = WORK / 'checkpoints'\n",
    "DATA_DIR = WORK / 'bubbleml_data/tutorial_48x48'\n",
    "\n",
    "ALL_SEEDS = [42, 100, 1234, 2025, 9999, 7, 17, 314, 2718, 4242, 7777]\n",
    "MODELS = ['hybrid_tfno', 'hybrid_div']\n",
    "MANIFEST_PATH = WORK / 'recovery_manifest.json'\n",
    "\n",
    "def checkpoint_is_valid(path: pathlib.Path) -> bool:\n",
    '    """Return True when a checkpoint exists, is non-empty, and can be deserialized."""\n',
    "    if not path.is_file() or path.stat().st_size == 0:\n",
    "        return False\n",
    "\n",
    "    try:\n",
    "        # Prefer the safer weights-only loader.\n",
    "        torch.load(path, map_location='cpu', weights_only=True)\n",
    "        return True\n",
    "    except Exception:\n",
    "        # Some older checkpoints may contain non-tensor metadata. For recovery\n",
    "        # inventory only, a normal deserialize is an acceptable compatibility fallback.\n",
    "        try:\n",
    "            torch.load(path, map_location='cpu', weights_only=False)\n",
    "            return True\n",
    "        except Exception:\n",
    "            return False\n",
    "\n",
    "def build_recovery_manifest() -> dict:\n",
    "    manifest = {\n",
    "        'completed_seeds': {model: [] for model in MODELS},\n",
    "        'valid_checkpoints': [],\n",
    "        'missing_or_corrupt': [],\n",
    "        'data_ready': DATA_DIR.is_dir(),\n",
    "    }\n",
    "\n",
    "    if not DATA_DIR.is_dir():\n",
    "        raise FileNotFoundError(\n",
    "            f'Preprocessed data directory is missing: {DATA_DIR}. '\n",
    "            'Cells 0-2 must be completed before rerunning from Cell 3.'\n",
    "        )\n",
    "\n",
    "    print('--- Forensic Inventory ---')\n",
    "    for model in MODELS:\n",
    "        for seed in ALL_SEEDS:\n",
    "            exp_path = EXP_DIR / f'hybrid_retrain_{model}' / f'{model}_seed_{seed}' / 'results.json'\n",
    "            chk_path = CHK_DIR / f'hybrid_retrain_{model}' / f'{model}_seed_{seed}.pt'\n",
    "\n",
    "            completed = False\n",
    "            if exp_path.is_file() and chk_path.is_file():\n",
    "                try:\n",
    "                    with exp_path.open('r', encoding='utf-8') as f:\n",
    "                        result = json.load(f)\n",
    "                    completed = (result.get('status') == 'completed') and checkpoint_is_valid(chk_path)\n",
    "                except Exception as exc:\n",
    "                    print(f'Warning: cannot validate {model} seed {seed}: {exc}')\n",
    "\n",
    "            if completed:\n",
    "                manifest['completed_seeds'][model].append(seed)\n",
    "                manifest['valid_checkpoints'].append(str(chk_path))\n",
    "            else:\n",
    "                manifest['missing_or_corrupt'].append(f'{model}_seed_{seed}')\n",
    "\n",
    "    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + '\\n', encoding='utf-8')\n",
    "\n",
    "    print('Inventory Table:')\n",
    "    print('| Model | Completed / Total | Remaining |')\n",
    "    print('| --- | ---: | ---: |')\n",
    "    for model in MODELS:\n",
    "        completed = len(manifest['completed_seeds'][model])\n",
    "        remaining = len(ALL_SEEDS) - completed\n",
    "        print(f'| {model} | {completed} / {len(ALL_SEEDS)} | {remaining} |')\n",
    "\n",
    "    return manifest\n",
    "\n",
    "recovery_manifest = build_recovery_manifest()\n",
    "print(f'Recovery manifest written to: {MANIFEST_PATH}')\n",
    "print('Cell 4 validation complete.')\n",
]

CELL5_LINES = [
    "import json\n",
    "import os\n",
    "import pathlib\n",
    "import subprocess\n",
    "import sys\n",
    "import time\n",
    "\n",
    "WORK = pathlib.Path('/kaggle/working')\n",
    "REPO = WORK / 'bubbleml-submission'\n",
    "DATA48 = WORK / 'bubbleml_data/tutorial_48x48'\n",
    "MANIFEST_PATH = WORK / 'recovery_manifest.json'\n",
    "\n",
    "ALL_SEEDS = [42, 100, 1234, 2025, 9999, 7, 17, 314, 2718, 4242, 7777]\n",
    "\n",
    "if not REPO.is_dir():\n",
    "    raise FileNotFoundError(\n",
    "        f'Repository not found: {REPO}. Complete Cells 0-2 before rerunning from Cell 3.'\n",
    "    )\n",
    "if not DATA48.is_dir():\n",
    "    raise FileNotFoundError(\n",
    "        f'Preprocessed data not found: {DATA48}. Complete Cells 0-2 before rerunning from Cell 3.'\n",
    "    )\n",
    "\n",
    "def validate_training_cli():\n",
    '    """Fail early if the pinned checkout does not expose the training interface used below."""\n',
    "    probe = subprocess.run(\n",
    "        [sys.executable, '-m', 'bubbleml_benchmark.paper_train', '--help'],\n",
    "        cwd=str(REPO),\n",
    "        capture_output=True,\n",
    "        text=True,\n",
    "        env={**os.environ, 'PYTHONUNBUFFERED': '1'},\n",
    "    )\n",
    "    if probe.returncode != 0:\n",
    "        raise RuntimeError(\n",
    "            'paper_train --help failed before training started. '\n",
    "            f'Exit code: {probe.returncode}.\\nSTDERR:\\n{probe.stderr[-4000:]}'\n",
    "        )\n",
    "\n",
    "    help_text = probe.stdout + '\\n' + probe.stderr\n",
    "    required_flags = [\n",
    "        '--data-dir', '--experiment-dir', '--checkpoints-dir', '--seeds',\n",
    "        '--models', '--max-epochs', '--min-epochs', '--batch-size',\n",
    "        '--history-size', '--future-size', '--learning-rate', '--weight-decay',\n",
    "        '--warmup-fraction', '--step-factor', '--step-patience-epochs',\n",
    "        '--gradient-clip', '--requested-modes', '--fno-width', '--fno-layers',\n",
    "        '--tfno-rank', '--domain-padding', '--plateau-window',\n",
    "        '--plateau-patience-windows', '--plateau-relative-delta', '--device',\n",
    "        '--lambda-div',\n",
    "    ]\n",
    "    missing_flags = [flag for flag in required_flags if flag not in help_text]\n",
    "    if missing_flags:\n",
    "        raise RuntimeError(\n",
    "            'The pinned paper_train CLI is missing expected option(s): '\n",
    "            + ', '.join(missing_flags)\n",
    "        )\n",
    "    print('paper_train CLI compatibility check PASSED.')\n",
    "\n",
    "validate_training_cli()\n",
    "\n",
    "def refresh_manifest():\n",
    "    # Cell 4 defines the canonical scanner; calling it again here makes Cell 5\n",
    "    # resilient to partial training runs without requiring Cell 4 to be rerun manually.\n",
    "    global recovery_manifest\n",
    "    recovery_manifest = build_recovery_manifest()\n",
    "    return recovery_manifest\n",
    "\n",
    "def verify_seed_artifacts(model_type: str, seed: int):\n",
    '    """Require both the completed result record and a readable checkpoint for this exact seed."""\n',
    "    exp_path = WORK / 'experiments' / f'hybrid_retrain_{model_type}' / f'{model_type}_seed_{seed}' / 'results.json'\n",
    "    chk_path = WORK / 'checkpoints' / f'hybrid_retrain_{model_type}' / f'{model_type}_seed_{seed}.pt'\n",
    "\n",
    "    if not exp_path.is_file():\n",
    "        raise RuntimeError(f'Training exited successfully but results.json is missing: {exp_path}')\n",
    "    try:\n",
    "        with exp_path.open('r', encoding='utf-8') as f:\n",
    "            result = json.load(f)\n",
    "    except Exception as exc:\n",
    "        raise RuntimeError(f'Cannot read training result file {exp_path}: {exc}') from exc\n",
    "\n",
    "    if result.get('status') != 'completed':\n",
    "        raise RuntimeError(\n",
    "            f'Training exited successfully but {exp_path} has status={result.get(\"status\")!r}, not \"completed\".'\n",
    "        )\n",
    "\n",
    "    if not chk_path.is_file() or chk_path.stat().st_size == 0:\n",
    "        raise RuntimeError(f'Training exited successfully but checkpoint is missing/empty: {chk_path}')\n",
    "\n",
    "    # Use the same validation routine defined in Cell 4.\n",
    "    checkpoint_validator = globals().get('checkpoint_is_valid')\n",
    "    if checkpoint_validator is None:\n",
    "        raise RuntimeError(\n",
    "            'checkpoint_is_valid is not available. Rerun from Cell 3 so Cells 3-4 are initialized.'\n",
    "        )\n",
    "    if not checkpoint_validator(chk_path):\n",
    "        raise RuntimeError(f'Checkpoint exists but could not be deserialized safely: {chk_path}')\n",
    "\n",
    "    return exp_path, chk_path\n",
    "\n",
    "def train_one_seed(model_type: str, seed: int, lambda_div=None):\n",
    "    cmd = [\n",
    "        sys.executable, '-m', 'bubbleml_benchmark.paper_train',\n",
    "        '--data-dir', str(DATA48),\n",
    "        '--experiment-dir', str(WORK / 'experiments' / f'hybrid_retrain_{model_type}'),\n",
    "        '--checkpoints-dir', str(WORK / 'checkpoints' / f'hybrid_retrain_{model_type}'),\n",
    "        '--seeds', str(seed),\n",
    "        '--models', model_type,\n",
    "        '--max-epochs', '200',\n",
    "        '--min-epochs', '20',\n",
    "        '--batch-size', '8',\n",
    "        '--history-size', '5',\n",
    "        '--future-size', '5',\n",
    "        '--learning-rate', '0.001',\n",
    "        '--weight-decay', '0.01',\n",
    "        '--warmup-fraction', '0.03',\n",
    "        '--step-factor', '0.5',\n",
    "        '--step-patience-epochs', '75',\n",
    "        '--gradient-clip', '1.0',\n",
    "        '--requested-modes', '24',\n",
    "        '--fno-width', '64',\n",
    "        '--fno-layers', '4',\n",
    "        '--tfno-rank', '0.1',\n",
    "        '--domain-padding', '0.1',\n",
    "        '--plateau-window', '5',\n",
    "        '--plateau-patience-windows', '2',\n",
    "        '--plateau-relative-delta', '0.001',\n",
    "        '--device', 'cuda',\n",
    "    ]\n",
    "    if lambda_div is not None:\n",
    "        cmd.extend(['--lambda-div', str(lambda_div)])\n",
    "\n",
    "    env = os.environ.copy()\n",
    "    env['PYTHONUNBUFFERED'] = '1'\n",
    "\n",
    "    print(f'\\n=== Training {model_type} | seed={seed} ===')\n",
    "    print('Command:', ' '.join(cmd))\n",
    "    started = time.time()\n",
    "    subprocess.run(cmd, check=True, cwd=str(REPO), env=env)\n",
    "    elapsed = time.time() - started\n",
    "\n",
    "    exp_path, chk_path = verify_seed_artifacts(model_type, seed)\n",
    "    print(f'Completed and verified {model_type} seed {seed} in {elapsed / 60:.1f} min.')\n",
    "    print(f'  results: {exp_path}')\n",
    "    print(f'  checkpoint: {chk_path}')\n",
    "\n",
    "def train_missing(model_type: str, lambda_div=None):\n",
    "    # Re-scan immediately before training so an interrupted prior run cannot cause\n",
    "    # already-completed seeds to be repeated.\n",
    "    manifest = refresh_manifest()\n",
    "    completed = set(manifest['completed_seeds'][model_type])\n",
    "    missing = [seed for seed in ALL_SEEDS if seed not in completed]\n",
    "\n",
    "    if not missing:\n",
    "        print(f'All {len(ALL_SEEDS)} seeds are already complete for {model_type}.')\n",
    "        return []\n",
    "\n",
    "    failures = []\n",
    "    for seed in missing:\n",
    "        try:\n",
    "            train_one_seed(model_type, seed, lambda_div=lambda_div)\n",
    "        except subprocess.CalledProcessError as exc:\n",
    "            print(\n",
    "                f'FAILED: {model_type} seed {seed} '\n",
    "                f'(subprocess exit code {exc.returncode}). Continuing to the next seed.'\n",
    "            )\n",
    "            failures.append(seed)\n",
    "        except Exception as exc:\n",
    "            print(f'FAILED: {model_type} seed {seed}: {exc}. Continuing to the next seed.')\n",
    "            failures.append(seed)\n",
    "\n",
    "    # Re-scan after the model finishes so the manifest reflects actual disk state.\n",
    "    final_manifest = refresh_manifest()\n",
    "    final_completed = set(final_manifest['completed_seeds'][model_type])\n",
    "    still_missing = [seed for seed in ALL_SEEDS if seed not in final_completed]\n",
    "\n",
    "    print(\n",
    "        f'{model_type}: {len(final_completed)}/{len(ALL_SEEDS)} complete; '\n",
    "        f'still missing: {still_missing or \"none\"}; '\n",
    "        f'seed subprocess failures: {failures or \"none\"}'\n",
    "    )\n",
    "\n",
    "    # A failed subprocess is always a hard failure for this model, even when\n",
    "    # a stale-looking artifact happens to exist on disk.\n",
    "    if failures:\n",
    "        raise RuntimeError(\n",
    "            f'{model_type} had training subprocess failures for seed(s): {failures}. '\n",
    "            'Inspect the preceding log and rerun Cell 5 to retry only the incomplete seeds.'\n",
    "        )\n",
    "\n",
    "    return still_missing\n",
    "\n",
    "# 1) zero-penalty hybrid (hybrid_tfno)\n",
    "tfno_missing = train_missing('hybrid_tfno')\n",
    "# 2) divergence-regularized hybrid (hybrid_div, lambda_div=0.30)\n",
    "div_missing = train_missing('hybrid_div', lambda_div=0.30)\n",
    "\n",
    "if tfno_missing or div_missing:\n",
    "    raise RuntimeError(\n",
    "        'Training finished with incomplete seeds. '\n",
    "        f'hybrid_tfno missing={tfno_missing}; hybrid_div missing={div_missing}. '\n",
    "        'Rerun Cell 5 to resume only the missing/corrupt seeds.'\n",
    "    )\n",
    "\n",
    "print('All requested training seeds completed successfully.')\n",
]

CELL6_LINES = [
    "import datetime\n",
    "import json\n",
    "import pathlib\n",
    "import platform\n",
    "import shutil\n",
    "import subprocess\n",
    "import torch\n",
    "\n",
    "WORK = pathlib.Path('/kaggle/working')\n",
    "REPO = WORK / 'bubbleml-submission'\n",
    "BRES = WORK / 'benchmark_results/hybrid_retrain'\n",
    "BRES.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "if not REPO.is_dir():\n",
    "    raise FileNotFoundError(f'Repository not found: {REPO}. Complete Cells 0-2 first.')\n",
    "\n",
    "# --- Hardware / software record ---\n",
    "gpu_count = torch.cuda.device_count()\n",
    "hardware = {\n",
    "    'timestamp_utc': datetime.datetime.now(datetime.timezone.utc).isoformat(),\n",
    "    'python': platform.python_version(),\n",
    "    'torch': torch.__version__,\n",
    "    'cuda_runtime': torch.version.cuda,\n",
    "    'cuda_available': torch.cuda.is_available(),\n",
    "    'cuda_device_count': gpu_count,\n",
    "    'gpu_names': [torch.cuda.get_device_name(i) for i in range(gpu_count)],\n",
    "    'platform': platform.platform(),\n",
    "}\n",
    "(BRES / 'hardware.json').write_text(\n",
    "    json.dumps(hardware, indent=2) + '\\n',\n",
    "    encoding='utf-8',\n",
    ")\n",
    "\n",
    "# --- Verify expected training outputs before packaging ---\n",
    "expected = {\n",
    "    'hybrid_tfno': WORK / 'experiments/hybrid_retrain_hybrid_tfno',\n",
    "    'hybrid_div': WORK / 'experiments/hybrid_retrain_hybrid_div',\n",
    "}\n",
    "\n",
    "missing_sources = [name for name, path in expected.items() if not path.is_dir()]\n",
    "if missing_sources:\n",
    "    raise FileNotFoundError(\n",
    "        'Cannot package results because these experiment directories are missing: '\n",
    "        + ', '.join(missing_sources)\n",
    "    )\n",
    "\n",
    "# Reuse Cell 4's scanner so the final packaging step verifies every requested seed.\n",
    "final_manifest = build_recovery_manifest()\n",
    "incomplete = {\n",
    "    model: [seed for seed in ALL_SEEDS if seed not in final_manifest['completed_seeds'][model]]\n",
    "    for model in MODELS\n",
    "}\n",
    "if any(incomplete.values()):\n",
    "    raise RuntimeError(f'Cannot package incomplete training results: {incomplete}')\n",
    "\n",
    "# --- Mirror experiment results into the checked-out repository ---\n",
    "for model, source in expected.items():\n",
    "    destination = REPO / 'experiments' / source.name\n",
    "    if destination.exists():\n",
    "        if destination.is_dir():\n",
    "            shutil.rmtree(destination)\n",
    "        else:\n",
    "            destination.unlink()\n",
    "    shutil.copytree(source, destination)\n",
    "\n",
    "# Checkpoint files are intentionally excluded from git.\n",
    "gitignore = REPO / '.gitignore'\n",
    "gitignore_text = gitignore.read_text(encoding='utf-8') if gitignore.exists() else ''\n",
    "if 'checkpoints/' not in gitignore_text.splitlines():\n",
    "    separator = '\\n' if gitignore_text and not gitignore_text.endswith('\\n') else ''\n",
    "    gitignore.write_text(\n",
    "        gitignore_text + separator + '\\n# Training checkpoints (not committed)\\ncheckpoints/\\n',\n",
    "        encoding='utf-8',\n",
    "    )\n",
    "\n",
    "# Save the manifest inside the repository as well.\n",
    "(REPO / 'recovery_manifest.json').write_text(\n",
    "    json.dumps(final_manifest, indent=2) + '\\n',\n",
    "    encoding='utf-8',\n",
    ")\n",
    "\n",
    "# --- Optional push ---\n",
    "pat = ''\n",
    "try:\n",
    "    from kaggle_secrets import UserSecretsClient\n",
    "    pat = UserSecretsClient().get_secret('GITHUB_PAT') or ''\n",
    "except Exception:\n",
    "    pass\n",
    "\n",
    "if not pat:\n",
    "    print('GITHUB_PAT not available; skipping git push.')\n",
    "else:\n",
    "    public_remote = 'https://github.com/RealmeBTI/bubbleml-submission.git'\n",
    "    auth_remote = f'https://x-token-auth:{pat}@github.com/RealmeBTI/bubbleml-submission.git'\n",
    "\n",
    "    subprocess.run(['git', 'config', 'user.email', 'sbmahafujbondhon@gmail.com'], check=True, cwd=REPO)\n",
    "    subprocess.run(['git', 'config', 'user.name', 'Bondhon'], check=True, cwd=REPO)\n",
    "    subprocess.run(['git', 'remote', 'set-url', 'origin', auth_remote], check=True, cwd=REPO)\n",
    "\n",
    "    try:\n",
    "        subprocess.run(['git', 'add', '-A'], check=True, cwd=REPO)\n",
    "        staged = subprocess.run(['git', 'diff', '--cached', '--quiet'], cwd=REPO)\n",
    "        if staged.returncode == 0:\n",
    "            print('No new repository changes to commit.')\n",
    "        else:\n",
    "            subprocess.run(\n",
    "                ['git', 'commit', '-m', 'Add retrained hybrid models (CUDA)'],\n",
    "                check=True,\n",
    "                cwd=REPO,\n",
    "            )\n",
    "            fetch = subprocess.run(\n",
    "                ['git', 'fetch', '--quiet', 'origin', 'hybrid-retrain-results'],\n",
    "                cwd=REPO,\n",
    "                stdout=subprocess.PIPE,\n",
    "                stderr=subprocess.PIPE,\n",
    "                text=True,\n",
    "            )\n",
    "            remote_ref = 'refs/remotes/origin/hybrid-retrain-results'\n",
    "            if fetch.returncode == 0 and subprocess.run(\n",
    "                ['git', 'show-ref', '--verify', '--quiet', remote_ref], cwd=REPO\n",
    "            ).returncode == 0:\n",
    "                remote_oid = subprocess.check_output(\n",
    "                    ['git', 'rev-parse', remote_ref], cwd=REPO, text=True\n",
    "                ).strip()\n",
    "                push_cmd = [\n",
    "                    'git', 'push',\n",
    "                    f'--force-with-lease=refs/heads/hybrid-retrain-results:{remote_oid}',\n",
    "                    'origin', 'HEAD:hybrid-retrain-results',\n",
    "                ]\n",
    "            else:\n",
    "                push_cmd = ['git', 'push', 'origin', 'HEAD:hybrid-retrain-results']\n",
    "\n",
    "            subprocess.run(push_cmd, check=True, cwd=REPO)\n",
    "            print('Pushed results to remote branch hybrid-retrain-results.')\n",
    "    finally:\n",
    "        # Never leave the PAT embedded in .git/config.\n",
    "        subprocess.run(['git', 'remote', 'set-url', 'origin', public_remote], check=True, cwd=REPO)\n",
    "\n",
    "print('\\nPackaging complete.')\n",
    "print(f'Results mirrored to: {REPO / \"experiments\"}')\n",
    "print(f'Hardware report: {BRES / \"hardware.json\"}')\n",
]

nb = {
    "cells": [
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": CELL0},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": CELL1},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": CELL2},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": CELL3_LINES},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": CELL4_LINES},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": CELL5_LINES},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": CELL6_LINES},
    ],
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.12"},
        "kaggle": {
            "accelerator": "gpu",
            "dataSources": [],
            "isInternetEnabled": True,
            "language": "python",
            "sourceType": "notebook",
            "isGpuEnabled": True
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

out_path = "kaggle_hybrid_retrain/kaggle_hybrid_retrain.ipynb"
with open(out_path, "w") as f:
    json.dump(nb, f, indent=1)
print(f"Notebook written to {out_path}")
